In [37]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree

df = pd.read_csv("merged.csv")

df.head(10)

,user,gender,fb_friend_count,sender_count,recipient_count,caller_count,callee_count,label
0,0.0,0.0,19.0,62.0,74.0,3.0,6.0,2.0
1,1.0,-1.0,6.0,2.0,1.0,0.0,0.0,1.0
2,2.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0
3,3.0,0.0,18.0,147.0,147.0,11.0,10.0,1.0
4,4.0,0.0,30.0,82.0,69.0,24.0,20.0,1.0
5,5.0,0.0,26.0,21.0,18.0,1.0,5.0,2.0
6,6.0,1.0,18.0,46.0,34.0,11.0,6.0,2.0
7,7.0,1.0,6.0,0.0,0.0,1.0,0.0,0.0
8,8.0,0.0,6.0,13.0,17.0,7.0,8.0,1.0
9,9.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0

In [44]:
df_num_feat = df[["fb_friend_count", 
                  "sender_count", 
                  "recipient_count", 
                  "caller_count", 
                  "callee_count"]]

normalized_df_subset=(df_num_feat-df_num_feat.min())/(df_num_feat.max()-df_num_feat.min())

normalized_df_subset.head(10)

df = pd.concat(df[["user", "gender", "label"]], )

   fb_friend_count  sender_count  recipient_count  caller_count  callee_count
0         0.188119      0.039117         0.046658      0.031915      0.059406
1         0.059406      0.001262         0.000631      0.000000      0.000000
2         0.069307      0.000000         0.000000      0.000000      0.000000
3         0.178218      0.092744         0.092686      0.117021      0.099010
4         0.297030      0.051735         0.043506      0.255319      0.198020
5         0.257426      0.013249         0.011349      0.010638      0.049505
6         0.178218      0.029022         0.021438      0.117021      0.059406
7         0.059406      0.000000         0.000000      0.010638      0.000000
8         0.059406      0.008202         0.010719      0.074468      0.079208
9         0.019802      0.000631         0.000000      0.000000      0.000000